stages:
  - build
  - test
#  - deploy

#default:
#  image: python:3.12.5-alpine3.19

build_a:
  stage: build
  script:
    - echo "This job builds container."
    - docker stop pyserver
    - docker rm pyserver
    - docker rmi pyserver
    - docker build -t pyserver:latest .
    - docker run -d -p 80:8181 pyserver

#build_b:
#  stage: build
#  script:
#    - echo "This job builds something else."

test_a:
  stage: test
  script:
    - echo "This job tests something. It will only run when all jobs in the"
    - echo "build stage are complete."
    - curl 'http://localhost:8181/'

#test_b:
#  stage: test
#  script:
#    - echo "This job tests something else. It will only run when all jobs in the"
#    - echo "build stage are complete too. It will start at about the same time as test_a."
#
#deploy_a:
#  stage: deploy
#  script:
#    - echo "This job deploys something. It will only run when all jobs in the"
#    - echo "test stage complete."
#  environment: production
#
#deploy_b:
#  stage: deploy
#  script:
#    - echo "This job deploys something else. It will only run when all jobs in the"
#    - echo "test stage complete. It will start at about the same time as deploy_a."
#  environment: production
